### ISSUE TITLE
Update Readme with example showing degit

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [fidisys/react-native-boilerplate#18]
Using [degit](https://github.com/Rich-Harris/degit) we can take a repo as template and create our own. It will be good to have an example in readme showcasing it.

Link for degit --> https://github.com/Rich-Harris/degit

``npx degit fidisys/react-native-boilerplate <project-name>``

**Comment by vspedr** [comment]
Hi, I want to work on this issue
